###############################################################
#  Generated by:      Cadence Innovus 23.33-s082_1
#  OS:                Linux x86_64(Host ID cadstation4.ktu.local)
#  Generated on:      Tue Jul 29 17:13:25 2025
#  Design:            ibex_simple_system
#  Command:           write_io_file -locations ibex_simple_system.save.io
###############################################################

(globals
    version = 3
    io_order = default
)
(iopad
	(topright
	(inst name="CornerCell2" cell=corner offset=0 orientation=r90 place_status=placed )
	)
    (top
	(inst  name="VSSPAD1"			offset=310  place_status=placed cell=gndpad)
	(inst  name="VSSPAD2"			offset=470 	place_status=placed cell=gndpad)
	(inst  name="GPIO[2].pad_io"	offset=630	place_status=placed )
	(inst  name="GPIO[1].pad_io"	offset=790	place_status=placed )
	(inst  name="GPIO[0].pad_io"	offset=950	place_status=placed )
	(inst  name="VDDPAD2"			offset=1110	place_status=placed cell=vddpad)
    )
	(bottomright
	(inst name="CornerCell3" cell=corner offset=0 orientation=r0 place_status=placed )
	)
    (right
	(inst  name="GPIO[9].pad_io"	offset=310 	place_status=placed )
	(inst  name="VSSCORE2"			offset=470	place_status=placed cell=gndcore)
	(inst  name="pad_clk_sys"		offset=630	place_status=placed )
	(inst  name="pad_test_mode"		offset=790 	place_status=placed )
	(inst  name="pad_rst_sys"		offset=950  place_status=placed )
	(inst  name="VDDCORE1"			offset=1110	place_status=placed cell=vddcore)
	(inst  name="VDDPAD3"			offset=1270	place_status=placed cell=vddpad)
    )
	(topleft
	(inst name = "CornerCell1" cell=corner offset=0 orientation=r180 place_status=placed)
	)
    (left
	(inst  name="GPIO[7].pad_io"	offset=310 	place_status=placed )
	(inst  name="GPIO[6].pad_io"	offset=470 	place_status=placed )
	(inst  name="GPIO[5].pad_io"	offset=630 	place_status=placed )
	(inst  name="VDDCORE2"			offset=790 	place_status=placed cell=vddcore)
	(inst  name="VSSCORE1"			offset=950	place_status=placed cell=gndcore)
	(inst  name="GPIO[4].pad_io"	offset=1110 place_status=placed )
	(inst  name="GPIO[3].pad_io"	offset=1270 place_status=placed )
    )
	(bottomleft
	(inst name="CornerCell4" cell=corner offset=0 orientation=r270 place_status=placed )
	)
    (bottom
	(inst  name="VDDPAD1"			offset=310  place_status=placed cell=vddpad)
	(inst  name="GPIO[8].pad_io"	offset=470 	place_status=placed )
	(inst  name="pad_SCL"			offset=630 	place_status=placed )
	(inst  name="pad_SDA"			offset=790 	place_status=placed )
	(inst  name="VSSPAD3"			offset=950  place_status=placed cell=gndpad)
	(inst  name="VSSPAD4"			offset=1110 place_status=placed cell=gndpad)
    )
)