PROGRAM = timer_handler_and_callback

COMMON_DIR := $(abspath ../../common)

C_SOURCES = 				\
core/src/main.c 		\
core/src/int.c			\
drivers/src/timer.c	\

C_INCLUDES =  \
-Icore/inc		\
-Idrivers/inc	\

include $(COMMON_DIR)/common.mk