PROGRAM = imem_hop

COMMON_DIR := $(abspath ../../common)

C_SOURCES = 			\
core/src/main.c 	\
core/src/int.c		\
driver/src/gpio.c \

C_INCLUDES =  \
-Icore/inc		\
-Idriver/inc	\

include $(COMMON_DIR)/common.mk