PROGRAM = gpio_display

COMMON_DIR := $(abspath ../../common)

C_SOURCES =  \
core/src/gpio.c \
core/src/int.c

C_INCLUDES =  \
-Icore/inc


#OBJS = $(patsubst %.c,$(BUILD_DIR)%.o,$(SRCS))

include $(COMMON_DIR)/common.mk
