# Program name here.
PROGRAM = clean_project

# Set 'common' directory realtive path.
COMMON_DIR := $(abspath ../../common)

# Source files.
C_SOURCES = 			\
core/src/main.c 	\
core/src/int.c

# Header files.
C_INCLUDES =  \
-Icore/inc

# This MUST be at the end of the Makefile.
include $(COMMON_DIR)/common.mk