#ifndef __TEST_H
#define __TEST_H

enum TEST_STATE {
  TEST_STATE_START,
  TEST_STATE_WAIT_GPIO_8_IRQ,
  TEST_STATE_SET_GPIO_0,
  TEST_STATE_SET_TIMER,
  TEST_STATE_WAIT_TIMER_IRQ,
  TEST_STATE_SET_GPIO_1,
  TEST_STATE_I2C_WRITE_TO_EEPROM,
  TEST_STATE_SET_GPIO_2,
  TEST_STATE_I2C_READ_FROM_EEPROM,
  TEST_STATE_SET_GPIO_3,
  TEST_STATE_CHECK_RW_DATA,
  TEST_STATE_SET_GPIO_4,
  TEST_STATE_UART_TX,
  TEST_STATE_UART_TX_WAIT_CPLT,
  TEST_STATE_UART_TX_CPLT,
  TEST_STATE_SET_GPIO_5,
  TEST_STATE_UART_RX,
  TEST_STATE_SET_GPIO_6,
  TEST_STATE_FINISH
};

#endif  // __TEST_H